
# ~/.tmux.conf

unbind C-b                                  # 기본 키 바인딩 제거
set-option -g prefix C-a                    # 기본 키 바인딩 Ctrl-a 로 설정
bind-key C-a send-prefix

unbind '"'
unbind %

# switch panes using Alt-arrow without prefix

bind -n M-Left select-pane -L               # 왼쪽 창으로 이동
bind -n M-Right select-pane -R              # 오른쪽 창으로 이동
bind -n M-Up select-pane -U                 # 위쪽 창으로 이동
bind -n M-Down select-pane -D               # 아래쪽 창으로 이동



# Default terminal
set -g default-terminal "screen-256color"

# Allow true color
set-option -ga terminal-overrides ",xterm-256color:Tc"

# 스크롤백 버퍼 크기 설정
set -g history-limit 10000

# 마우스 스크롤 활성화
set -g mouse on

# vi 스타일의 복사 모드 사용
setw -g mode-keys vi

# 복사 모드에서 스크롤 키 바인딩
bind -T copy-mode-vi M-Up send-keys -X scroll-up
bind -T copy-mode-vi M-Down send-keys -X scroll-down
bind -T copy-mode-vi M-PageUp send-keys -X halfpage-up
bind -T copy-mode-vi M-PageDown send-keys -X halfpage-down
bind -T copy-mode-vi PageDown send-keys -X page-down
bind -T copy-mode-vi PageUp send-keys -X page-up

# tmux와 시스템 클립보드 통합
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind C-c run "tmux save-buffer - | pbcopy"  # Ctrl-C로 복사
